image: node:18

stages:
  - build
  - pages

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm ci
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 1 week

pages:
  stage: pages
  dependencies:
    - build
  script:
    - echo "Publishing public/ to GitLab Pages"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
